In [1]:
import scanpy as sc
import pandas as pd

In [2]:
adata = sc.read_h5ad("/project2/gilad/jpopp/ebQTL/data/single_cell_objects/highpass/eb_raw.h5ad")

In [3]:
adata.obs

,sample_id,Collection.Date,Lane,Sample.ID,cDNA.amp.cycles,cDNA.total.yield,library.prep.batch,Sequencing.batch,col.group,donor_id,...,comments,collection.date,collection.group.label,EB.appearance.notes,dissociated.by.,approx..time.in.accumax..in.minutes.,leiden_coarse,sizeFactor,scranGroup,scranCluster
cell,,,,,,,,,,,,,,,,,,,,,
AAACCCACACGGCGTT-1,1001_1,10/1/2020,1,100120_1,11.0,393.02,1,1,100120,NA18870,...,NaN,10/1/2020,100120.0,"variable size, some translucent areas, some da...",kenneth,35.0,0,0.505477,0,0_1
AAACCCACAGAAGTGC-1,1001_1,10/1/2020,1,100120_1,11.0,393.02,1,1,100120,NA18870,...,NaN,10/1/2020,100120.0,"variable size, some translucent areas, some da...",kenneth,35.0,0,2.970244,0,0_6
AAACGAAAGGTATTGA-1,1001_1,10/1/2020,1,100120_1,11.0,393.02,1,1,100120,NA18870,...,NaN,10/1/2020,100120.0,"variable size, some translucent areas, some da...",kenneth,35.0,1,1.034802,0,0_8
AAACGAAAGTAGATCA-1,1001_1,10/1/2020,1,100120_1,11.0,393.02,1,1,100120,NA18913,...,NaN,10/1/2020,100120.0,"manys EBs, variable size, no dark spots",katie,15.0,1,0.256048,0,0_2
AAACGAACACCCTCTA-1,1001_1,10/1/2020,1,100120_1,11.0,393.02,1,1,100120,NA19190,...,NaN,10/1/2020,100120.0,"few large EBs, some colored spots",katie,25.0,1,0.172881,0,0_9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGGTTTCGAAGCCC-118,0911_4,9/11/2019,4,091119_4,NaN,NaN,P3,P3,91119,NA18511,...,NaN,NaN,91119.0,NaN,NaN,NaN,2,0.815209,4,4_17
TTTGGTTTCGAGATAA-118,0911_4,9/11/2019,4,091119_4,NaN,NaN,P3,P3,91119,NA18858,...,NaN,NaN,91119.0,NaN,NaN,NaN,2,0.896352,4,4_21
TTTGTTGAGGATATAC-118,0911_4,9/11/2019,4,091119_4,NaN,NaN,P3,P3,91119,NA18511,...,NaN,NaN,91119.0,NaN,NaN,NaN,0,0.835484,4,4_16
TTTGTTGGTTTGGAGG-118,0911_4,9/11/2019,4,091119_4,NaN,NaN,P3,P3,91119,NA18511,...,NaN,NaN,91119.0,NaN,NaN,NaN,1,0.368702,4,4_7
TTTGTTGTCCTCTCGA-118,0911_4,9/11/2019,4,091119_4,NaN,NaN,P3,P3,91119,NA18511,...,NaN,NaN,91119.0,NaN,NaN,NaN,1,0.311549,4,4_4

In [8]:
metadata = adata.obs[['Collection.Date', 'donor_id', 'sample_id', 'library.prep.batch']]

In [9]:
metadata.drop_duplicates().to_csv("/project2/gilad/jpopp/ebQTL/temp/metadata_from_anndata.tsv", sep="\t")